# WordPress — HTTPS con dominio de Cloudflare
server {
    listen 80;
    server_name fhdproyects.innc.link;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name fhdproyects.innc.link;
    ssl_certificate     /etc/nginx/certs/certpub.pem;
    ssl_certificate_key /etc/nginx/certs/certpriv.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    root /var/www/html;
    index index.php index.html;
    client_max_body_size 64M;

    location ~* \.(jpg|jpeg|png|gif|webp|css|js|ico|svg|woff|woff2)$ {
        expires 30d;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~ /\. { deny all; }
}


# Laravel — HTTPS con dominio privado DNS
server {
    listen 80;
    server_name tallerfhd.gestiona;
    return 301 https://tallerfhd.gestiona$request_uri;
}
server {
    listen 443 ssl;
    server_name tallerfhd.gestiona;
    ssl_certificate     /etc/nginx/certs/certpub.pem;
    ssl_certificate_key /etc/nginx/certs/certpriv.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    root /var/www/panel/public;
    index index.php;
    client_max_body_size 64M;

    location = / {
        return 301 /admin;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location ~ /\. { deny all; }
}
